/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpravaKrviApp {
    }
}
declare global {
    interface HTMLSpravaKrviAppElement extends Components.SpravaKrviApp, HTMLStencilElement {
    }
    var HTMLSpravaKrviAppElement: {
        prototype: HTMLSpravaKrviAppElement;
        new (): HTMLSpravaKrviAppElement;
    };
    interface HTMLElementTagNameMap {
        "sprava-krvi-app": HTMLSpravaKrviAppElement;
    }
}
declare namespace LocalJSX {
    interface SpravaKrviApp {
    }
    interface IntrinsicElements {
        "sprava-krvi-app": SpravaKrviApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sprava-krvi-app": LocalJSX.SpravaKrviApp & JSXBase.HTMLAttributes<HTMLSpravaKrviAppElement>;
        }
    }
}
