/* tslint:disable */
/* eslint-disable */
/**
 * Blood management API
 * Management of blood donors and blood units
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xsykoram3@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

